$("input[type=password]").parent().append("<div id='derp'>herp</div>")
//$("#derp").css("position","absolute")
//$("#derp").css("right","0px")
//$("#derp").css("top","0px")
//$("#derp").css("z-index","9001")
$("#derp").show()
console.log("stuff is done")
