$("input[type=password]").css("position","relative")
$("input[type=password]").append("<div id='derp'>herp</div>")
$("#derp").css("position","absolute")
$("#derp").css("right","0px")
$("#derp").css("top","0px")
